[package]
name = "deco"
version = "0.1.0"
authors = ["Emīls Piņķis <pinkisemils@gmail.com>"]
build = "build.rs"

[dependencies]
image = "*"
libc = "0.2"
jpeg-decoder = "0.1"

[build-dependencies]
gcc = "0.3"
